- name: Install Zabbix Agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Restart Zabbix Agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
