#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: ubuntu
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4ncefgQIGIpzQEEWLFgZKfabIA3aHSb3vCSozmutnpyAetJm4HzYil0/tD+ARoMgCDFoFRCtvkMZG1rrG2OzE9tRcVXVBxUF3tKCIegZbScq/PH9FyR4ciov8V1fLebjGTsxfVQyOLAH5umNDDPPZCIOd+sEFTPZa2cTFf8wihv/K3QKcWAAdSu13t0mUMajKY/ICLe661pJZ/A7R71tjuHMqng+Cxt5HYsQh4P7KBc6yh09JeHIQ/yaDYRf05LpD3TodQNzbbPAS2d0HNAMQAKNTBiKEwoJr+Sg5GYaBT4v3089BNxESZljp3079QwEQdeNgwdlCpDinYH4Xo1LeEkMrR4r6wLzwo8UCaIjG0DqrQ8opQrXcpzkWTKIvrIxUMQuVLQHOK6fp1m0Thw8hb6BmR1cT3Ek/F2CLmE2jQ8j1iBy8hoBGDgdyvnzVfFdgE2+bdVARZ16ra39OocfdxFhvmN/vVEyZ03F3dN6e0KhkawBgz02BzX2lFu8Z3YE= bulushkin@HELP1-NPC
write_files:
  - path: "/usr/local/etc/startup.sh"
    permissions: "755"
    content: |
      #!/bin/bash

      apt update
      apt -y install software-properties-common
      add-apt-repository --yes --update ppa:ansible/ansible
      apt -y install ansible
    defer: true
runcmd:
  - ["/usr/local/etc/startup.sh"]
